---
- name: "Copy config files | {{ playbook_app }}"
  ansible.builtin.copy:
    src: "{{ (item.alt_app | default(playbook_app)) + '/' + item.name }}"
    dest: "{{ dockerdir ~ '/' ~ (item.alt_app | default(playbook_app)) ~ '/' ~ (item.path ~ '/' if item.path is defined and item.path else '') ~ item.name }}"
    owner: "{{ item.user | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default('0644') }}"
  register: "deploy_config"
  with_items: "{{ deploy_configlist }}"
  when: deploy_configlist is defined and deploy_configlist | length > 0

- name: "Generate config files from templates | {{ playbook_app }}"
  ansible.builtin.template:
    src: "{{ (item.alt_app | default(playbook_app)) + '/' + item.name }}.j2"
    dest: "{{ dockerdir ~ '/' ~ (item.alt_app | default(playbook_app)) ~ '/' ~ (item.path ~ '/' if item.path is defined and item.path else '') ~ item.name }}"
    owner: "{{ item.user | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items: "{{ deploy_templatelist }}"
  when: deploy_templatelist is defined and deploy_templatelist | length > 0
