---

- name: "{{ playbook_app }} | Copy config files"
  ansible.builtin.copy:
    src: "{{ (item.alt_app | default(playbook_app)) + '/' + item.name }}"
    dest: "{{ dockerdir ~ '/' ~ (item.alt_app | default(playbook_app)) ~ '/' ~ (item.path ~ '/' if item.path is defined and item.path else '') ~ item.name }}"
    owner: "{{ item.user | default(ansible_user) }}"
    group: "{{ item.group | default(ansible_user) }}"
    mode: "{{ item.mode | default('0644') }}"
  register: "config"
  with_items: "{{ config_filelist }}"
  when: config_filelist is defined and config_filelist

- name: "{{ playbook_app }} | Generate config files from templates"
  ansible.builtin.template:
    src: "{{ (item.alt_app | default(playbook_app)) + '/' + item.name }}.j2"
    dest: "{{ dockerdir ~ '/' ~ (item.alt_app | default(playbook_app)) ~ '/' ~ (item.path ~ '/' if item.path is defined and item.path else '') ~ item.name }}"
    owner: "{{ item.user | default(ansible_user) }}"
    group: "{{ item.group | default(ansible_user) }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items: "{{ config_templatelist }}"
  when: config_templatelist is defined and config_templatelist
