---
- name: "{{ playbook_app }} | Create all the necessary directories and files"
  ansible.builtin.include_tasks:
    file: "vols2dirs.yml"
  vars:
    vols2dirs: "{{ deploy_volumes }}"
  when: deploy_volumes is defined and deploy_volumes

- name: "{{ playbook_app }} | Prepare config files"
  ansible.builtin.include_tasks:
    file: "configfiles.yml"
  vars:
    config_filelist: "{{ deploy_configlist }}"
    config_templatelist: "{{ deploy_templatelist }}"
  when:
    - (deploy_configlist is defined and deploy_configlist) or (deploy_templatelist is defined and deploy_templatelist)

- name: "{{ playbook_app }} | Deploy the dependencies"
  community.general.docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}:{{ item.tag }}"
    command: "{{ item.command | default(omit) }}"
    entrypoint: "{{ item.entrypoint | default(omit) }}"
    pull: "{{ item.pull | default(omit) }}"
    restart_policy: "{{ item.restart_policy | default('unless-stopped') }}"
    networks: "{{ item.networks | default(omit) }}"
    network_mode: "{{ item.network_mode | default(omit) }}"
    healthcheck: "{{ item.healthcheck | default(omit) }}"
    capabilities: "{{ item.capabilities | default(omit) }}"
    security_opt: "{{ item.security_opt | default(omit) }}"
    privileged: "{{ item.privileged | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    env: "{{ item.env | default(omit) }}"
    ports: "{{ item.ports | default(omit) }}"
    hostname: "{{ item.hostname | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    devices: "{{ item.devices | default(omit) }}"
    auto_remove: "{{ item.auto_remove | default(omit) }}"
    recreate: "{{ item.recreate | default(omit) }}"
    log_driver: "{{ log_driver | default(omit) }}"
    log_opt: "{{ log_opt | default(omit) }}"
  with_items: "{{ deploy_deps }}"
  when:
    - deploy_deps is defined and deploy_deps
    - deploy_deps_run

- name: "{{ playbook_app }} | Deploy the main container"
  community.general.docker_container:
    name: "{{ playbook_app }}"
    image: "{{ deploy_image }}:{{ deploy_image_tag }}"
    command: "{{ deploy_command | default(omit) }}"
    entrypoint: "{{ deploy_entrypoint | default(omit) }}"
    pull: "{{ deploy_pull | default(omit) }}"
    restart_policy: "{{ deploy_restart_policy | default('unless-stopped') }}"
    networks: "{{ deploy_networks | default(omit) }}"
    network_mode: "{{ deploy_network_mode | default(omit) }}"
    healthcheck: "{{ deploy_healthcheck | default(omit) }}"
    capabilities: "{{ deploy_capabilities | default(omit) }}"
    security_opt: "{{ deploy_security_opt | default(omit) }}"
    privileged: "{{ deploy_privileged | default(omit) }}"
    user: "{{ deploy_user | default(omit) }}"
    env: "{{ deploy_env | default(omit) }}"
    ports: "{{ deploy_ports | default(omit) }}"
    hostname: "{{ deploy_hostname | default(omit) }}"
    volumes: "{{ deploy_volumes | default(omit) }}"
    devices: "{{ deploy_devices | default(omit) }}"
    auto_remove: "{{ deploy_auto_remove | default(omit) }}"
    recreate: "{{ deploy_recreate | default(omit) }}"
    log_driver: "{{ log_driver | default(omit) }}"
    log_opt: "{{ log_opt | default(omit) }}"

- name: "{{ playbook_app }} | Finishing commands"
  ansible.builtin.raw: "{{ deploy_finish }}"
  when: deploy_finish is defined and deploy_finish
