---
- name: "Vols2dirs | Empty out the dir list"
  ansible.builtin.set_fact:
    all_paths: []

- name: "Vols2dirs | Get the path for directory on the host"
  ansible.builtin.set_fact:
    all_paths: "{{ vols2dirs | map('split', ':') | map('first') | list }}"
    create_dirs: "{{ lookup('vars', playbook_app + '_create_dirs', default=[]) }}"

- name: "Vols2dirs | Split files and dirs"
  set_fact:
    dir_paths: "{{ (all_paths | reject('regex', '\\..{2,5}$') | list) + create_dirs }}"
    file_paths: "{{ all_paths | select('regex', '\\..{2,5}$') | reject('search', '.sock') | list }}"

- name: "Vols2dirs | Create necessary dirs"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
  loop: "{{ dir_paths }}"
  when: item is regex('^/')

- name: "Vols2dirs | Create parent directories for files"
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    state: "directory"
  loop: "{{ file_paths }}"
  when: item is regex('^/') and (item | dirname) != '/'

- name: "Vols2dirs | Create files if they don't exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: "touch"
    access_time: "preserve"
    modification_time: "preserve"
  loop: "{{ file_paths }}"
