---

dependency:
  name: galaxy
  options:
    requirements-file: molecule/deploy/requirements.yml

driver:
  name: default
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local

platforms:
  - name: localhost

provisioner:
  name: ansible
  playbooks:
    prepare: ${MOLECULE_SCENARIO_DIRECTORY}/prepare.yml
    converge: ${MOLECULE_SCENARIO_DIRECTORY}/converge.yml
    cleanup: ${MOLECULE_SCENARIO_DIRECTORY}/cleanup.yml

verifier:
  name: testinfra
  options:
    sudo: False

scenario:
  name: deploy
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
