---

dependency:
  name: galaxy
  options:
    requirements-file: molecule/deploy/requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    privileged: true
    pre_build_image: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /tmp:/tmp

provisioner:
  name: ansible
  lint: |
    yamllint .
    ansible-lint
  playbooks:
    prepare: ${MOLECULE_SCENARIO_DIRECTORY}/prepare.yml
    converge: ${MOLECULE_SCENARIO_DIRECTORY}/converge.yml

verifier:
  name: testinfra
  options:
    sudo: false

scenario:
  name: deploy
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
