---
- name: "Set up docker networks"
  ansible.builtin.include_tasks: networks.yml
  when: docker_net_setup is defined and docker_net_setup

- name: "Set up docker TLS"
  ansible.builtin.include_tasks: tls.yml
  when: docker_tls_setup is defined and docker_tls_setup

- name: "Configure Docker daemon"
  ansible.builtin.include_tasks: config.yml
  when: (docker_tls_setup is defined and docker_tls_setup) or (docker_config_setup is defined and docker_config_setup)

- name: "Validate Docker TLS setup"
  ansible.builtin.include_tasks: validate.yml
  when: docker_tls_setup is defined and docker_tls_setup
